### PR TITLE
Added boost_signals fix

### PR DESCRIPTION
**Pull request by hansbonini**
boost signals are removed from recent boost releases. i made a fix for this package too. Look at PR #1

### CODE REVIEW

**Comment by bionade24** [comment]
As described in our project, we only accept PRs with the official ROS releases as source. This also solves the problem for most packages. You also forgot to generate the `.SRCINFO` file.

**Comment by hansbonini** [comment]
> As described in our project, we only accept PRs with the official ROS releases as source. This also solves the problem for most packages. You also forgot to generate the `.SRCINFO` file.

The ```.SRCINFO``` doesn't need to be changed.

**Comment by bionade24** [comment]
When you make your change the other things, it has. As I said, with the other source this patch is probably unnecessary.

**Comment by hansbonini** [comment]
> When you make your change the other things, it has. As I said, with the other source this patch is probably unnecessary.

No, it's not. If the source has changed the package will not break. Trust me.
If ```signals``` is no more found in the ```CMakeLists.txt```, the ```sed``` command does'nt affect anything.

**Comment by acxz** [comment]
@hansbonini that is true, but I don't think @bionade24 was getting at that.
First off, the PR you submitted uses an unofficial source for the source code, which is **not** something we should do.
Second off, the way you went about fixing the signals issue is a bit messy. The cleaner solution would be to patch it. Take a look at my PR [here](https://github.com/ros-melodic-arch/ros-melodic-tf2/commit/583151ad3e127427adc80c29356ebe17d83aa6e5) and [here](https://github.com/ros-melodic-arch/ros-melodic-tf/pull/4).
Thank you for the PRs in the first place, we do need to fix these packages, but we would like to fix them the right way instead of some unofficial, hacky, messy way.
If you could go ahead and rework your PRs we would appreciate it much! Once again thank you, and let's do this properly.

**Comment by bionade24** [comment]
Thanks. When I wrote those things, I just didn't had the time to explain it further, so I directed to the project guidelines. I've currently an issue open at the source code repo, since it isn't already removed, it would be nice if you vote for it. https://github.com/ros-perception/laser_filters/pull/77

**Comment by bionade24** [comment]
Unnecessary since https://github.com/ros-melodic-arch/ros-melodic-laser-filters/pull/2 got merged.

**Pull request closed without merging**
